"""
    ECE 461 - Fall 2021 - Project 2 - Team 24

    Expanded API for ECE 461/Fall 2021/Project 2/Team 24: A Trustworthy Module Registry  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: gonza487@purdue.edu
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.package_data import PackageData
from openapi_client.model.package_metadata import PackageMetadata
globals()['PackageData'] = PackageData
globals()['PackageMetadata'] = PackageMetadata
from openapi_client.model.package import Package


class TestPackage(unittest.TestCase):
    """Package unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackage(self):
        """Test Package"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Package()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
