runtime: python39 

instance_class: F2

entrypoint: python3 -m openapi_server

env_variables:
  GOOGLE_CLOUD_PROJECT: ece-461-proj-2-24
  BIGQUERY_DATASET: module_registry
  GITHUB_TOKEN: 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
