runtime: python39 

instance_class: F2

env_variables:
  GOOGLE_CLOUD_PROJECT: ece-461-proj-2-24
  BIGQUERY_DATASET: module_registry

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
