# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.user import User
from openapi_server.models.user_authentication_info import UserAuthenticationInfo


class AuthenticationRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuthenticationRequest - a model defined in OpenAPI

        user: The user of this AuthenticationRequest.
        secret: The secret of this AuthenticationRequest.
    """

    user: User
    secret: UserAuthenticationInfo

AuthenticationRequest.update_forward_refs()
