# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PackageMetadata(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PackageMetadata - a model defined in OpenAPI

        name: The name of this PackageMetadata.
        version: The version of this PackageMetadata.
        id: The id of this PackageMetadata.
        sensitive: The sensitive of this PackageMetadata [Optional].
        secret: The secret of this PackageMetadata [Optional].
    """

    name: str
    version: str
    id: str
    sensitive: Optional[bool] = None
    secret: Optional[bool] = None

PackageMetadata.update_forward_refs()
