# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.package_metadata import PackageMetadata
from openapi_server.models.user import User


class PackageHistoryEntry(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PackageHistoryEntry - a model defined in OpenAPI

        user: The user of this PackageHistoryEntry.
        date: The date of this PackageHistoryEntry.
        package_metadata: The package_metadata of this PackageHistoryEntry.
        action: The action of this PackageHistoryEntry.
    """

    user: User
    date: datetime
    package_metadata: PackageMetadata
    action: str

PackageHistoryEntry.update_forward_refs()
