# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.package_data import PackageData
from openapi_server.models.package_metadata import PackageMetadata


class Package(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Package - a model defined in OpenAPI

        metadata: The metadata of this Package.
        data: The data of this Package.
    """

    metadata: PackageMetadata
    data: PackageData

Package.update_forward_refs()
