# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from pydantic.fields import Field


class PackageMetadata(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PackageMetadata - a model defined in OpenAPI

        name: The name of this PackageMetadata.
        version: The version of this PackageMetadata.
        id: The id of this PackageMetadata.
        sensitive: The sensitive of this PackageMetadata [Optional].
        secret: The secret of this PackageMetadata [Optional].
    """

    name: str = Field(..., alias='Name')
    version: str = Field(..., alias='Version')
    id: str = Field(..., alias='ID')
    sensitive: Optional[bool] = Field(None, alias='Sensitive')
    secret: Optional[bool] = Field(None, alias='Secret')

PackageMetadata.update_forward_refs()
