# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.user_authentication_info import UserAuthenticationInfo
from openapi_server.models.user_group import UserGroup
from pydantic.fields import Field


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        name: The name of this User.
        is_admin: The is_admin of this User.
        user_authentication_info: The user_authentication_info of this User [Optional].
        user_group: The user_group of this User [Optional].
        id: The id of this User [Optional].
    """

    name: str
    is_admin: bool = Field(..., alias='isAdmin')
    user_authentication_info: Optional[UserAuthenticationInfo] = None
    user_group: Optional[UserGroup] = None
    id: Optional[int] = None

User.update_forward_refs()
