# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class UserGroup(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserGroup - a model defined in OpenAPI

        name: The name of this UserGroup.
        upload: The upload of this UserGroup.
        search: The search of this UserGroup.
        download: The download of this UserGroup.
        register: The register of this UserGroup.
    """

    name: str
    upload: bool
    search: bool
    download: bool
    register: bool

UserGroup.update_forward_refs()
