# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from pydantic.fields import Field


class UserGroup(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserGroup - a model defined in OpenAPI

        name: The name of this UserGroup.
        upload: The upload of this UserGroup.
        search: The search of this UserGroup.
        download: The download of this UserGroup.
        create_user: The create_user of this UserGroup.
        id: The id of this UserGroup [Optional].
    """

    name: str = Field(..., alias='Name')
    upload: bool = Field(..., alias='Upload')
    search: bool = Field(..., alias='Search')
    download: bool = Field(..., alias='Download')
    create_user: bool = Field(..., alias='CreateUser')
    id: Optional[int] = Field(None, alias='ID')

UserGroup.update_forward_refs()
