name: Deploy 
on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: actions/labeler@v2
        with:
          repo-token: "AIzaSyCyR6UgZLT8opbrjRSaskRTUZK08jeoA7I"
