name: Deploy 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deply to google engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ece-461-proj-2-24
          version: master
          credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
          flags: --no-cache
