name: PyTest
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    name: PyTest
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/requirements.txt
          pip install ./server
      - name: Test Server
        run: |
          export GOOGLE_CLOUD_PROJECT=${{secrets.GOOGLE_PROJECT_ID}}
          export BIGQUERY_DATASET=module_registry
          export GOOGLE_APPLICATION_CREDENTIALS=${{secrets.GOOGLE_APP_ENGINE_KEY}}
          pytest server
      - name: Test Scorer
        run: |
          pytest scorer
      - name: Test Frontend
        run: |
          pytest frontend
          
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
              type: "python,java"
#        env:
#              WORKSPACE: https://github.com/${{ REPO }}/blob/${{ github.sha }}
#              GITHUB_TOKEN: ${{ secrets.TOKEN }}
#              SCAN_AUTO_BUILD: true
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
